"use client";

import { useState } from "react";
import { Loader2, Wifi, WifiOff, ArrowRight, Sparkles, BarChart3, Mail } from "lucide-react";
import Header from "@/components/Header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { fetchHello } from "@/lib/api";

const FEATURES = [
  {
    icon: Sparkles,
    title: "Lead Enrichment",
    description: "Demographics, walkability, economic data, and company news — pulled automatically from public APIs.",
  },
  {
    icon: BarChart3,
    title: "Lead Scoring",
    description: "0–100 score based on market health, renter density, and geographic fit for EliseAI's ICP.",
  },
  {
    icon: Mail,
    title: "Outreach Drafts",
    description: "Personalized intro emails generated by Claude AI using enriched lead context.",
  },
];

export default function Home() {
  const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [message, setMessage] = useState<string | null>(null);

  async function handlePing() {
    setStatus("loading");
    setMessage(null);
    try {
      const data = await fetchHello();
      setMessage(data.message);
      setStatus("success");
    } catch (err) {
      setMessage(err instanceof Error ? err.message : "Unknown error");
      setStatus("error");
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      <main className="flex-1 flex flex-col items-center px-6 py-20">

        {/* Hero */}
        <div className="text-center mb-16 max-w-2xl w-full">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 text-xs font-semibold text-primary bg-primary/10 border border-primary/25 rounded-full px-3 py-1.5 mb-8">
            <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse-slow" />
            AI-Powered Sales Intelligence
          </div>

          <h1 className="text-5xl sm:text-6xl font-extrabold text-foreground tracking-tight mb-5 leading-[1.1]">
            Enrich leads.
            <br />
            <span className="bg-gradient-brand bg-clip-text text-transparent">
              Close faster.
            </span>
          </h1>

          <p className="text-muted-foreground text-lg leading-relaxed max-w-lg mx-auto">
            Upload an inbound lead list and get back enriched profiles, smart scores,
            and ready-to-send outreach — powered by public APIs and Claude AI.
          </p>
        </div>

        {/* Feature cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 w-full max-w-3xl mb-14">
          {FEATURES.map(({ icon: Icon, title, description }) => (
            <div
              key={title}
              className="rounded-xl border border-border bg-card p-5 flex flex-col gap-3"
            >
              <div className="w-8 h-8 rounded-lg bg-primary/15 flex items-center justify-center">
                <Icon className="w-4 h-4 text-primary" />
              </div>
              <div>
                <p className="text-sm font-semibold text-foreground mb-1">{title}</p>
                <p className="text-xs text-muted-foreground leading-relaxed">{description}</p>
              </div>
            </div>
          ))}
        </div>

        {/* API health card */}
        <Card className="w-full max-w-sm">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              {status === "success" ? (
                <Wifi className="w-4 h-4 text-emerald-400" />
              ) : status === "error" ? (
                <WifiOff className="w-4 h-4 text-red-400" />
              ) : (
                <Wifi className="w-4 h-4 text-muted-foreground" />
              )}
              API Connection
            </CardTitle>
            <CardDescription className="text-xs">
              Verify the backend is reachable before uploading leads.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <Button
              onClick={handlePing}
              disabled={status === "loading"}
              className="w-full font-semibold"
            >
              {status === "loading" ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Connecting…
                </>
              ) : (
                <>
                  Ping API
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </Button>

            {message && (
              <div
                className={`rounded-lg px-3.5 py-3 text-xs font-mono border leading-relaxed ${
                  status === "success"
                    ? "bg-emerald-950/40 border-emerald-800/60 text-emerald-300"
                    : "bg-red-950/40 border-red-800/60 text-red-300"
                }`}
              >
                <span className="font-bold mr-1.5">
                  {status === "success" ? "✓" : "✗"}
                </span>
                {message}
              </div>
            )}
          </CardContent>
        </Card>

        <p className="mt-8 text-xs text-muted-foreground text-center">
          Lead upload and enrichment coming next
          <ArrowRight className="inline w-3 h-3 ml-1 mb-0.5" />
        </p>

      </main>
    </div>
  );
}
